Repository CHEE-UP/TWL, pull requests merged in 2020-02, with the labels that each got.

#8 [soomin] 200207
  soomin/200207.md
Labels: algorithm, django, tech-interview

#9 [jisoo] 200207
  jisoo/200207.md
Labels: algorithm, django, tech-interview

#11 [soomin] 200210 daily todo
  soomin/200210.md
Labels: django, tech-interview

#10 [jisoo] 200210
  jisoo/200210.md
Labels: algorithm, django, tech-interview

#12 [jisoo] 200211
  jisoo/200211.md
Labels: algorithm, django, tech-interview

#13 [soomin] 200211 daily to do
  soomin/200211.md
Labels: django, tech-interview

#14 [jisoo] 200212
  jisoo/200212.md
Labels: algorithm, django, tech-interview

#16 [jisoo] 200213
  jisoo/200213.md
Labels: algorithm

#17 [jisoo] 200214
  jisoo/200214.md
Labels: algorithm, django, tech-interview

#15 [soomin] 200212 daily to do
  soomin/200212.md
  soomin/200214.md
Labels: algorithm, django, tech-interview

#18 [jisoo] 200215
  jisoo/200215.md
Labels: algorithm, tech-interview

#20 [jisoo] 200217
  jisoo/200217.md
Labels: algorithm, tech-interview

#19 [yeji] 200217
  yeji/200214.md
  yeji/200217.md
Labels: algorithm, django

#21 [jisoo] 200218
  jisoo/200218.md
Labels: algorithm, django, tech-interview

#22 200218 daily to do
  soomin/200218.md
Labels: prography, tech-interview

#24 [jisoo] 200219
  jisoo/200219.md
Labels: algorithm, tech-interview

#23 200219 daily to do
  yeji/200219.md
Labels: algorithm

#27 [yeji]200220
  yeji/200220.md
Labels: algorithm, django

#25 [jisoo] 200220
  jisoo/200220.md
Labels: algorithm, django, tech-interview

#28 [soomin] 200220 dailytodo
  soomin/200219.md
  soomin/200220.md
Labels: prography, tech-interview

#30 [jisoo] 200221
  jisoo/200221.md
Labels: algorithm

#29 [yeji] 200221
  yeji/200221.md
Labels: algorithm

#33 [yeji] 200224
  yeji/200224.md
Labels: algorithm, django

#35 [yeji] 200225
  yeji/200225.md
Labels: algorithm, django

#31 [soomin] 200221 daily todo
  soomin/200221.md
  soomin/200224.md
Labels: algorithm, ios, tech-interview

#36 [yeji]200227
  yeji/200227.md
Labels: algorithm, django
