Repository CHEE-UP/TWL, pull requests merged in 2020-04, with the labels that each got.

#49 [jisoo] 2020_04_01
  jisoo/2020_04_1week.md
Labels: algorithm, tech-interview

#51 Yeji
  yeji/200405_1week.md
Labels: algorithm

#50 [jisoo] 2020_04_2 week
  jisoo/2020_04_2week.md
Labels: algorithm, django, tech-interview
